
const mongoose = require('mongoose');
const express= require('express');
const app = express();
app.use(express.json())
require('dotenv').config();
const{ScrapDataRoutes}=require('./routes/data.route')
app.use(ScrapDataRoutes)
mongoose.connect(process.env.DB_URL)
const db = mongoose.connection
db.on("error", () => console.log("ERROR while connecting to DB"))  //code for connecting mongodb
db.once("open", () => {console.log("Connected to mongoDB ")
})


app.listen(8080,()=> 
console.log('Running at localhost:8000'));




// program to extract value as an array from an array of objects



    // {LT[0],LT[1],LT[2],LT[3],LT[4],LT[5],LT[6],LT[7],LT[8],LT[9],LT[10],LT[11],LT[12],moment().format('l'),moment().format('LT')} 
    // {HDFCBANK[0],HDFCBANK[1],HDFCBANK[2], HDFCBANK [3],HDFCBANK[4], HDFCBANK [5], HDFCBANK [6],HDFCBANK[7],HDFCBANK[8],HDFCBANK[9],HDFCBANK[10],HDFCBANK[11],HDFCBANK [12],moment().format('l'),moment().format('LT')}
    // {HDFC[0], HDFC[1],  HDFC[2], HDFC[3],HDFC[4], HDFC[5], HDFC[6],HDFC[7],HDFC[8],HDFC[9],HDFC[10],HDFC[11],HDFC[12],moment().format('l'),moment().format('LT')}
    // {ITC[0],ITC[1],ITC[2],ITC[3],ITC[4], ITC[5], ITC[6],ITC[7],ITC[8],ITC[9],ITC[10],ITC[11], ITC[12],moment().format('l'),moment().format('LT')}
    // {HDFCLIFE[0], HDFCLIFE[1], HDFCLIFE[2],  HDFCLIFE[3],HDFCLIFE[4],HDFCLIFE[5],  HDFCLIFE[6],HDFCLIFE[7],HDFCLIFE[8],HDFCLIFE[9],HDFCLIFE[10],HDFCLIFE[11],HDFCLIFE[12],moment().format('l'),moment().format('LT')}
    // {TITAN[0],TITAN[1], TITAN[2], TITAN[3],TITAN[4], TITAN[5],TITAN[6],TITAN[7],TITAN[8],TITAN[9],TITAN[10],TITAN[11],TITAN[12],moment().format('l'),moment().format('LT')}
    // {TCS[0], TCS[1], TCS[2], TCS[3],TCS[4],TCS[5],  TCS[6],TCS[7],TCS[8],TCS[9],TCS[10],TCS[11], TCS[12],moment().format('l'),moment().format('LT')}
    // {BAJFINANCE[0],BAJFINANCE[1],BAJFINANCE[2], BAJFINANCE[3],BAJFINANCE[4],  BAJFINANCE[5],  BAJFINANCE[6],BAJFINANCE[7],BAJFINANCE[8],BAJFINANCE[9],BAJFINANCE[10],BAJFINANCE[11], BAJFINANCE[12],moment().format('l'),moment().format('LT')}
    // {TATACONSUM[0],TATACONSUM[1], TATACONSUM[2], TATACONSUM[3],TATACONSUM[4],TATACONSUM[5],  TATACONSUM[6],TATACONSUM[7],TATACONSUM[8],TATACONSUM[9],TATACONSUM[10],TATACONSUM[11],TATACONSUM[12],moment().format('l'),moment().format('LT')}
    // {COALINDIA[0], COALINDIA[1], COALINDIA[2], COALINDIA[3],COALINDIA[4],COALINDIA[5],COALINDIA[6],COALINDIA[7],COALINDIA[8],COALINDIA[9],COALINDIA[10],COALINDIA[11], COALINDIA[12],moment().format('l'),moment().format('LT')}
    // {HCLTECH[0], HCLTECH[1], HCLTECH[2], HCLTECH[3],HCLTECH[4],HCLTECH[5],HCLTECH[6],HCLTECH[7],HCLTECH[8],HCLTECH[9],HCLTECH[10],HCLTECH[11], HCLTECH[12],moment().format('l'),moment().format('LT')}
    // {SUNPHARMA[0],SUNPHARMA[1], SUNPHARMA[2], SUNPHARMA[3],SUNPHARMA[4],SUNPHARMA[5], SUNPHARMA[6],SUNPHARMA[7],SUNPHARMA[8],SUNPHARMA[9],SUNPHARMA[10],SUNPHARMA[11], SUNPHARMA[12],moment().format('l'),moment().format('LT')}
    // {INFY[0], INFY[1], INFY[2], INFY[3],INFY[4],INFY[5],INFY[6],INFY[7],INFY[8],INFY[9],INFY[10],INFY[11],INFY[12],moment().format('l'),moment().format('LT')}
    // {KOTAKBANK[0], KOTAKBANK[1], KOTAKBANK[2], KOTAKBANK[3],KOTAKBANK[4],KOTAKBANK[5],  KOTAKBANK[6],KOTAKBANK[7],KOTAKBANK[8],KOTAKBANK[9],KOTAKBANK[10],KOTAKBANK[11], KOTAKBANK[12],moment().format('l'),moment().format('LT')}
    // {SBILIFE[0],SBILIFE[1], SBILIFE[2], SBILIFE[3],SBILIFE[4],SBILIFE[5],SBILIFE[6],SBILIFE[7],SBILIFE[8],SBILIFE[9],SBILIFE[10],SBILIFE[11],SBILIFE[12],moment().format('l')}
    // {WIPRO[0],WIPRO[1], WIPRO[2], WIPRO[3],WIPRO[4],WIPRO[5], WIPRO[6],WIPRO[7],WIPRO[8],WIPRO[9],WIPRO[10],WIPRO[11], WIPRO[12],moment().format('l'),moment().format('LT')}
    // {BRITANNIA[0],BRITANNIA[1],BRITANNIA[2],BRITANNIA[3],BRITANNIA[4],BRITANNIA[5],BRITANNIA[6],BRITANNIA[7],BRITANNIA[8],BRITANNIA[9],BRITANNIA[10],BRITANNIA[11],BRITANNIA[12],moment().format('l'),moment().format('LT')}
    // {TECHM[0],TECHM[1], TECHM[2], TECHM[3],TECHM[4],TECHM[5],TECHM[6],TECHM[7],TECHM[8],TECHM[9],TECHM[10],TECHM[11],TECHM[12],moment().format('l'),moment().format('LT')}
    // {HINDUNILVR[0],HINDUNILVR[1], HINDUNILVR[2], HINDUNILVR[3],HINDUNILVR[4], HINDUNILVR[5], HINDUNILVR[6],HINDUNILVR[7],HINDUNILVR[8],HINDUNILVR[9],HINDUNILVR[10],HINDUNILVR[11], HINDUNILVR[12],moment().format('l'),moment().format('LT')}
    // {TATASTEEL[0],TATASTEEL[1],TATASTEEL[2],TATASTEEL[3],TATASTEEL[4],TATASTEEL[5],TATASTEEL[6],TATASTEEL[7],TATASTEEL[8],TATASTEEL[9],TATASTEEL[10],TATASTEEL[11],TATASTEEL[12],moment().format('l')}
    // {ULTRACEMCO[0],ULTRACEMCO[1],ULTRACEMCO[2],ULTRACEMCO[3],ULTRACEMCO[4],ULTRACEMCO[5],ULTRACEMCO[6],ULTRACEMCO[7],ULTRACEMCO[8],ULTRACEMCO[9],ULTRACEMCO[10],ULTRACEMCO[11],ULTRACEMCO[12],moment().format('l'),moment().format('LT')}
    // {ONGC[0], ONGC[1], ONGC[2], ONGC[3],ONGC[4],  ONGC[5], ONGC[6],ONGC[7], ONGC[8], ONGC[9], ONGC[10], ONGC[11], ONGC[12],moment().format('l'),moment().format('LT')}
    // {JSWSTEEL[0], JSWSTEEL[1], JSWSTEEL[2],JSWSTEEL[3],JSWSTEEL[4],JSWSTEEL[5],JSWSTEEL[6],JSWSTEEL[7],JSWSTEEL[8],JSWSTEEL[9],JSWSTEEL[10],JSWSTEEL[11],JSWSTEEL[12],moment().format('l'),moment().format('LT')}
    // {CIPLA[0],CIPLA[1],CIPLA[2],CIPLA[3],CIPLA[4],CIPLA[5], CIPLA[6],CIPLA[7],CIPLA[8],CIPLA[9],CIPLA[10],CIPLA[11],CIPLA[12],moment().format('l'),moment().format('LT')}
    // {TATAMOTORS[0],TATAMOTORS[1],TATAMOTORS[2],TATAMOTORS[3],TATAMOTORS[4],TATAMOTORS[5],TATAMOTORS[6],TATAMOTORS[7],TATAMOTORS[8],TATAMOTORS[9],TATAMOTORS[10],TATAMOTORS[11],TATAMOTORS[12],moment().format('l'),moment().format('LT')}
    // {BHARTIARTL[0],BHARTIARTL[1],BHARTIARTL[2],BHARTIARTL[3],BHARTIARTL[4],BHARTIARTL[5],BHARTIARTL[6],BHARTIARTL[7],BHARTIARTL[8],BHARTIARTL[9],BHARTIARTL[10],BHARTIARTL[11],BHARTIARTL[12],moment().format('l'),moment().format('LT')}
    // {UPL[0],UPL[1],UPL[2],UPL[3],UPL[4],UPL[5],UPL[6],UPL[7],UPL[8],UPL[9],UPL[10],UPL[11],UPL[12],moment().format('l'),moment().format('LT')}
    // {BAJAJFINSV[0],BAJAJFINSV[1],BAJAJFINSV[2],BAJAJFINSV[3],BAJAJFINSV[4],BAJAJFINSV[5],BAJAJFINSV[6],BAJAJFINSV[7],BAJAJFINSV[8],BAJAJFINSV[9],BAJAJFINSV[10],BAJAJFINSV[11],BAJAJFINSV[12],moment().format('l'),moment().format('LT')}
    // {ADANIPORTS[0],ADANIPORTS[1],ADANIPORTS[2],ADANIPORTS[3],ADANIPORTS[4],ADANIPORTS[5],ADANIPORTS[6],ADANIPORTS[7],ADANIPORTS[8],ADANIPORTS[9],ADANIPORTS[10],ADANIPORTS[11],ADANIPORTS[12],moment().format('l'),moment().format('LT')}
    // {DIVISLAB[0],DIVISLAB[1],DIVISLAB[2],DIVISLAB[3],DIVISLAB[4],DIVISLAB[5],DIVISLAB[6],DIVISLAB[7],DIVISLAB[8],DIVISLAB[9],DIVISLAB[10],DIVISLAB[11],DIVISLAB[12],moment().format('l'),moment().format('LT')}
    // {BAJAJAUTO[0],BAJAJAUTO[1],BAJAJAUTO[2],BAJAJAUTO[3],BAJAJAUTO[4],BAJAJAUTO[5],BAJAJAUTO[6],BAJAJAUTO[7],BAJAJAUTO[8],BAJAJAUTO[9],BAJAJAUTO[10],BAJAJAUTO[11],BAJAJAUTO[12],moment().format('l'),moment().format('LT')}
    // {POWERGRID[0],POWERGRID[1],POWERGRID[2],POWERGRID[3],POWERGRID[4],POWERGRID[5],POWERGRID[6],POWERGRID[7],POWERGRID[8],POWERGRID[9],POWERGRID[10],POWERGRID[11],POWERGRID[12],moment().format('l'),moment().format('LT')}
    // {DRREDDY[0],DRREDDY[1],DRREDDY[2],DRREDDY[3],DRREDDY[4],DRREDDY[5],DRREDDY[6],DRREDDY[7],DRREDDY[8],DRREDDY[9],DRREDDY[10],DRREDDY[11],DRREDDY[12],moment().format('l'),moment().format('LT')}
    // {ASIANPAINT[0],ASIANPAINT[1],ASIANPAINT[2],ASIANPAINT[3],ASIANPAINT[4],ASIANPAINT[5],ASIANPAINT[6],ASIANPAINT[7],ASIANPAINT[8],ASIANPAINT[9],ASIANPAINT[10],ASIANPAINT[11],ASIANPAINT[12],moment().format('l'),moment().format('LT')}
    // {NESTLEIND[0],NESTLEIND[1],NESTLEIND[2],NESTLEIND[3],NESTLEIND[4],NESTLEIND[5],NESTLEIND[6],NESTLEIND[7],NESTLEIND[8],NESTLEIND[9],NESTLEIND[10],NESTLEIND[11],NESTLEIND[12],moment().format('l')}
    // {BPCL[0],BPCL[1],BPCL[2],BPCL[3],BPCL[4],BPCL[5],BPCL[6],BPCL[7],BPCL[8],BPCL[9],BPCL[10],BPCL[11],BPCL[12],moment().format('l'),moment().format('LT')}
    // {MandM[0],MandM[1],MandM[2],MandM[3],MandM[4],MandM[5],MandM[6],MandM[7],MandM[8],MandM[9],MandM[10],MandM[11],MandM[12],moment().format('l'),moment().format('LT')}
    // {GRASIM[0],GRASIM[1],GRASIM[2],GRASIM[3],GRASIM[4],GRASIM[5],GRASIM[6],GRASIM[7],GRASIM[8],GRASIM[9],GRASIM[10],GRASIM[11],GRASIM[12],moment().format('l'),moment().format('LT')}
    // {HEROMOTOCO[0],HEROMOTOCO[1],HEROMOTOCO[2],HEROMOTOCO[3],HEROMOTOCO[4],HEROMOTOCO[5],HEROMOTOCO[6],HEROMOTOCO[7],HEROMOTOCO[8],HEROMOTOCO[9],HEROMOTOCO[10],HEROMOTOCO[11],HEROMOTOCO[12],moment().format('l'),moment().format('LT')}
    // {HINDALCO[0],HINDALCO[1],HINDALCO[2],HINDALCO[3],HINDALCO[4],HINDALCO[5],HINDALCO[6],HINDALCO[7],HINDALCO[8],HINDALCO[9],HINDALCO[10],HINDALCO[11],HINDALCO[12],moment().format('l'),moment().format('LT')}
    // {ICICIBANK[0],ICICIBANK[1],ICICIBANK[2],ICICIBANK[3],ICICIBANK[4],ICICIBANK[5],ICICIBANK[6],ICICIBANK[7],ICICIBANK[8],ICICIBANK[9],ICICIBANK[10],ICICIBANK[11],ICICIBANK[12],moment().format('l'),moment().format('LT')}
    // {MARUTI[0],MARUTI[1],MARUTI[2],MARUTI[3],MARUTI[4],MARUTI[5],MARUTI[6],MARUTI[7],MARUTI[8],MARUTI[9],MARUTI[10],MARUTI[11],MARUTI[12],moment().format('l'),moment().format('LT')}
    // {AXISBANK[0],AXISBANK[1],AXISBANK[2],AXISBANK[3],AXISBANK[4],AXISBANK[5],AXISBANK[6],AXISBANK[7],AXISBANK[8],AXISBANK[9],AXISBANK[10],AXISBANK[11],AXISBANK[12],moment().format('l'),moment().format('LT')}
    // {RELIANCE[0],RELIANCE[1],RELIANCE[2],RELIANCE[3],RELIANCE[4],RELIANCE[5],RELIANCE[6],RELIANCE[7],RELIANCE[8],RELIANCE[9],RELIANCE[10],RELIANCE[11],RELIANCE[12],moment().format('l'),moment().format('LT')}
    // {APOLLOHOSP[0],APOLLOHOSP[1],APOLLOHOSP[2],APOLLOHOSP[3],APOLLOHOSP[4],APOLLOHOSP[5],APOLLOHOSP[6],APOLLOHOSP[7],APOLLOHOSP[8],APOLLOHOSP[9],APOLLOHOSP[10],APOLLOHOSP[11],APOLLOHOSP[12],moment().format('l'),moment().format('LT')}
    // {NTPC[0],NTPC[1],NTPC[2],NTPC[3],NTPC[4],NTPC[5],NTPC[6],NTPC[7],NTPC[8],NTPC[9],NTPC[10],NTPC[11],NTPC[12],moment().format('l'),moment().format('LT')}
    // {SBIN[0],SBIN[1],SBIN[2],SBIN[3],SBIN[4],SBIN[5],SBIN[6],SBIN[7],SBIN[8],SBIN[9],SBIN[10],SBIN[11],SBIN[12],moment().format('l'),moment().format('LT')}
    // {INDUSINDBK[0],INDUSINDBK[1],INDUSINDBK[2],INDUSINDBK[3],INDUSINDBK[4],INDUSINDBK[5],INDUSINDBK[6],INDUSINDBK[7],INDUSINDBK[8],INDUSINDBK[9],INDUSINDBK[10],INDUSINDBK[11],INDUSINDBK[12],moment().format('l'),moment().format('LT')}
    // {EICHERMOT[0],EICHERMOT[1],EICHERMOT[2],EICHERMOT[3],EICHERMOT[4],EICHERMOT[5],EICHERMOT[6],EICHERMOT[7],EICHERMOT[8],EICHERMOT[9],EICHERMOT[10],EICHERMOT[11],EICHERMOT[12],moment().format('l'),moment().format('LT')}
    // {ADANIENT[0],ADANIENT[1],ADANIENT[2],ADANIENT[3],ADANIENT[4],ADANIENT[5],ADANIENT[6],ADANIENT[7],ADANIENT[8],ADANIENT[9],ADANIENT[10],ADANIENT[11],ADANIENT[12],moment().format('l'),moment().format('LT')}